version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongPassword
    ports:
      - "1433:1433"
    networks:
      - mynetwork

  backend:
    build:
      context: .
    container_name: song-microservice
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=sql-server
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=Politecnica1
      - DB_NAME=MusicDB_New
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
