USE master;
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'MusicDB')
BEGIN
    CREATE DATABASE MusicDB;
END
GO

USE MusicDB;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Songs')
BEGIN
    CREATE TABLE Songs (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        Name NVARCHAR(255) NOT NULL,
        Path NVARCHAR(500) NOT NULL,
        Plays INT DEFAULT 0
    );
END
GO
